### PR TITLE
Use puppeteer instead of phantomjs

### PR DESCRIPTION
**Pull request by ramonszo**

### CODE REVIEW

**Comment by c0bra** [comment]
@ramon82 I've been waiting for screenshot-stream to update internally to use puppeteer but it looks more and more like that's not going to happen.

Your PR includes a bunch of lint errors. Can you run `yarn test` locally and get it cleaned up? Then I'll take a look. Thanks!

**Comment by ramonszo** [comment]
Ok!

**Comment by ramonszo** [comment]
Hey @c0bra I think there's some compatibility issues with your building system.. Can you check this? The code passes all tests

**Comment by c0bra** [comment]
@ramon82 ah yea, it's trying to run against node v4. Lemme disable that.

**Comment by c0bra** [comment]
I need to close and reopen this to get travis to update the config.

**Pull request merged**
